/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package manejo_cadenas;
import java.lang.Object;
import java.awt.Component;
import java.awt.Container;
import javax.swing.JComponent;

import java.io.File;
import java.awt.LayoutManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.io.*;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;





/**
 *
 * @author Sapón Pérez
 */
public class frm_cadenas_traductor extends javax.swing.JFrame {

    /**
     * Creates new form frm_cadenas_traductor
     */
    
    
    Analizar_texto analizar = new Analizar_texto();
    char aux;
    String result="",edit_opcion;
    int cant;
    
    Fichero fichero = new Fichero();
    public frm_cadenas_traductor() {
        initComponents();
        
        
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_input = new javax.swing.JTextArea();
        btn_func = new javax.swing.JButton();
        lbl_welcome = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_titulo2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        lbl12 = new javax.swing.JLabel();
        lbl14 = new javax.swing.JLabel();
        lbl15 = new javax.swing.JLabel();
        lbl16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_traduccion = new javax.swing.JTextArea();
        lbl_resultado = new javax.swing.JLabel();
        lbl_resultado2 = new javax.swing.JLabel();
        lbl_resultado3 = new javax.swing.JLabel();
        lbl_resultado4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_resultado5 = new javax.swing.JLabel();
        lbl_resultado6 = new javax.swing.JLabel();
        lbl_resultado7 = new javax.swing.JLabel();
        lbl_resultado8 = new javax.swing.JLabel();
        lbl_resultado9 = new javax.swing.JLabel();
        lbl_resultado10 = new javax.swing.JLabel();
        lbl_resultado11 = new javax.swing.JLabel();
        lbl_resultado12 = new javax.swing.JLabel();
        lbl_resultado13 = new javax.swing.JLabel();
        lbl_resultado14 = new javax.swing.JLabel();
        lbl_resultado15 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_archi = new javax.swing.JMenu();
        a_i1 = new javax.swing.JMenuItem();
        a_i2 = new javax.swing.JMenuItem();
        a_i3 = new javax.swing.JMenuItem();
        menu_edit = new javax.swing.JMenu();
        e_i1 = new javax.swing.JMenuItem();
        e_i2 = new javax.swing.JMenuItem();
        e_i3 = new javax.swing.JMenuItem();
        e_i4 = new javax.swing.JMenuItem();
        e_i5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_titulo.setText("Manejo de Cadenas");

        txta_input.setColumns(20);
        txta_input.setRows(5);
        jScrollPane1.setViewportView(txta_input);

        btn_func.setText("Procesar");
        btn_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_funcActionPerformed(evt);
            }
        });

        lbl_welcome.setText("Ingrese un texto o abra un archivo");

        lbl_titulo2.setText("TRADUCCION A CLAVE MURCIELAGO");

        lbl1.setText("Longitud del texto");

        lbl2.setText("Total palabras");

        lbl3.setText("Primer letra del texto");

        lbl4.setText("Ultima letra del texto");

        lbl5.setText("Letra central del texto");

        lbl6.setText("Primera palabra");

        lbl8.setText("Palabra central");

        lbl9.setText("Ultima palabra");

        lbl10.setText("Repeticion de \"A\", \"a\" ó \"á\"");

        lbl11.setText("Repeticion de \"E\", \"e\" ó \"é\"");

        lbl12.setText("Repeticion de \"I\", \"i\" ó \"í\"");

        lbl14.setText("Repeticion de \"U\", \"u\" ó \"ú\"");

        lbl15.setText("Palabras con cantidad de caracteres par");

        lbl16.setText("Palabras con cantidad de caracteres impar");

        txt_traduccion.setColumns(20);
        txt_traduccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_traduccion.setRows(5);
        jScrollPane2.setViewportView(txt_traduccion);

        lbl_resultado.setText(">>");

        lbl_resultado2.setText(">>");

        lbl_resultado3.setText(">>");

        lbl_resultado4.setText(">>");

        jLabel5.setText("Repeticion de \"O\",\"o\" u \"ó\"");

        lbl_resultado5.setText(">>");

        lbl_resultado6.setText(">>");

        lbl_resultado7.setText(">>");

        lbl_resultado8.setText(">>");

        lbl_resultado9.setText(">>");

        lbl_resultado10.setText(">>");

        lbl_resultado11.setText(">>");

        lbl_resultado12.setText(">>");

        lbl_resultado13.setText(">>");

        lbl_resultado14.setText(">>");

        lbl_resultado15.setText(">>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator8)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(btn_func))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(lbl_titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator9)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator5)
                    .addComponent(jSeparator7)
                    .addComponent(jSeparator6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_resultado6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(lbl15, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(lbl_resultado14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_resultado7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl16, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(lbl_resultado15))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_resultado4)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_resultado12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_resultado3)
                        .addGap(64, 64, 64)
                        .addComponent(lbl12, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_resultado11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_resultado5)
                        .addGap(62, 62, 62)
                        .addComponent(lbl14, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_resultado13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_resultado)
                        .addGap(65, 65, 65)
                        .addComponent(lbl10, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_resultado9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_resultado2)
                        .addGap(68, 68, 68)
                        .addComponent(lbl11, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_resultado10))
                    .addComponent(jSeparator12)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_resultado8)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_welcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_func)
                .addGap(8, 8, 8)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(lbl10)
                    .addComponent(lbl_resultado)
                    .addComponent(lbl_resultado9))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2)
                    .addComponent(lbl11)
                    .addComponent(lbl_resultado2)
                    .addComponent(lbl_resultado10))
                .addGap(14, 14, 14)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl12)
                    .addComponent(lbl3)
                    .addComponent(lbl_resultado3)
                    .addComponent(lbl_resultado11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl4)
                    .addComponent(lbl_resultado4)
                    .addComponent(jLabel5)
                    .addComponent(lbl_resultado12))
                .addGap(6, 6, 6)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_resultado5)
                    .addComponent(lbl5)
                    .addComponent(lbl14)
                    .addComponent(lbl_resultado13))
                .addGap(10, 10, 10)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl6)
                    .addComponent(lbl15)
                    .addComponent(lbl_resultado6)
                    .addComponent(lbl_resultado14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl8)
                    .addComponent(lbl_resultado7)
                    .addComponent(lbl_resultado15)
                    .addComponent(lbl16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl9)
                    .addComponent(lbl_resultado8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_titulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        menu_archi.setText("Archivo");

        a_i1.setText("Cargar");
        a_i1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_i1ActionPerformed(evt);
            }
        });
        menu_archi.add(a_i1);

        a_i2.setText("Guardar");
        a_i2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_i2ActionPerformed(evt);
            }
        });
        menu_archi.add(a_i2);

        a_i3.setText("Guardar como...");
        a_i3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_i3ActionPerformed(evt);
            }
        });
        menu_archi.add(a_i3);

        jMenuBar1.add(menu_archi);

        menu_edit.setText("Editar");

        e_i1.setText("Copiar (ctrl+c)");
        e_i1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_i1ActionPerformed(evt);
            }
        });
        menu_edit.add(e_i1);

        e_i2.setText("Pegar (ctrl+p)");
        e_i2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_i2ActionPerformed(evt);
            }
        });
        menu_edit.add(e_i2);

        e_i3.setText("Cortar (ctrl + x)");
        e_i3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_i3ActionPerformed(evt);
            }
        });
        menu_edit.add(e_i3);

        e_i4.setText("Buscar (ctrl + b)");
        e_i4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_i4ActionPerformed(evt);
            }
        });
        menu_edit.add(e_i4);

        e_i5.setText("Reemplazar (ctrl + r)");
        e_i5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_i5ActionPerformed(evt);
            }
        });
        menu_edit.add(e_i5);

        jMenuBar1.add(menu_edit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void e_i1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_i1ActionPerformed
        // TODO add your handling code here:
        edit_opcion=txta_input.getText();
        txta_input.selectAll();
        
    }//GEN-LAST:event_e_i1ActionPerformed

    private void e_i3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_i3ActionPerformed
        // TODO add your handling code here:
        edit_opcion = txta_input.getText();
        txta_input.setText("");
    }//GEN-LAST:event_e_i3ActionPerformed

    private void e_i4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_i4ActionPerformed
        // TODO add your handling code here:
       
       
       
       
        //instanciar aqui la palabra que voy a buscar
        
    }//GEN-LAST:event_e_i4ActionPerformed

    private void a_i3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_i3ActionPerformed
        // TODO add your handling code here:
        
         JFileChooser fc=new JFileChooser();
 
        //Indicamos que podemos seleccionar varios ficheros
        fc.setMultiSelectionEnabled(true);

        //Indicamos lo que podemos seleccionar
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        //Creamos el filtro
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.TXT", "txt");

        //Le indicamos el filtro
        fc.setFileFilter(filtro);
        
        
        //Abrimos la ventana, guardamos la opcion seleccionada por el usuario
        int seleccion=fc.showSaveDialog(this);
 
//Si el usuario, pincha en aceptar
        if(seleccion==JFileChooser.APPROVE_OPTION){
 
    //Seleccionamos el fichero
            File fichero=fc.getSelectedFile();
 

            
 
            try(FileWriter fr=new FileWriter(fichero)){
                fr.write(this.txta_input.getText());
                
            } catch (IOException e1) {
                e1.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_a_i3ActionPerformed

    private void a_i1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_i1ActionPerformed
        // TODO add your handling code here:
        
        JFileChooser fc=new JFileChooser();
 
        //Indicamos que podemos seleccionar varios ficheros
        fc.setMultiSelectionEnabled(true);

        //Indicamos lo que podemos seleccionar
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        //Creamos el filtro
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.TXT", "txt");

        //Le indicamos el filtro
        fc.setFileFilter(filtro);
        
        
        //Abrimos la ventana, guardamos la opcion seleccionada por el usuario
        int seleccion=fc.showOpenDialog(jPanel1);
 
//Si el usuario, pincha en aceptar
        if(seleccion==JFileChooser.APPROVE_OPTION){
 
    //Seleccionamos el fichero
            File fichero=fc.getSelectedFile();
 
    //Ecribe la ruta del fichero seleccionado en el campo de texto
            //txt_dir.setText(fichero.getAbsolutePath());
 
            try(FileReader fr=new FileReader(fichero)){
                String cadena="";
                int valor=fr.read();
                while(valor!=-1){
                    cadena=cadena+(char)valor;
                    valor=fr.read();
                    
                }
                
                txta_input.setText(cadena);
            } catch (IOException e1) {
                e1.printStackTrace();
            }
        }
       
    }//GEN-LAST:event_a_i1ActionPerformed

    private void a_i2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_i2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_a_i2ActionPerformed

    private void btn_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_funcActionPerformed
        // TODO add your handling code here:
        cant=analizar.palabras_longitud(txta_input.getText());
        lbl_resultado.setText(""+cant);

        cant=analizar.palabras_numero(txta_input.getText());
        lbl_resultado2.setText(""+cant);

        aux=analizar.caracter_primera(txta_input.getText());
        lbl_resultado3.setText(""+aux);

        aux=analizar.caracter_ultima(txta_input.getText());
        lbl_resultado4.setText(""+aux);

        aux=analizar.caracter_central(txta_input.getText());
        lbl_resultado5.setText(""+aux);

        result = analizar.palabra_primera(txta_input.getText());
        lbl_resultado6.setText(result);

        result=analizar.palabra_ultima(txta_input.getText());
        lbl_resultado8.setText(result);

        result = analizar.palabra_central(txta_input.getText());
        lbl_resultado7.setText(result);

        cant=analizar.numero_vocal_a(txta_input.getText());
        lbl_resultado9.setText(""+cant);

        cant=analizar.numero_vocal_e(txta_input.getText());
        lbl_resultado10.setText(""+cant);

        cant=analizar.numero_vocal_i(txta_input.getText());
        lbl_resultado11.setText(""+cant);

        cant=analizar.numero_vocal_o(txta_input.getText());
        lbl_resultado12.setText(""+cant);

        cant=analizar.numero_vocal_u(txta_input.getText());
        lbl_resultado13.setText(""+cant);

        cant = analizar.palabras_pares(txta_input.getText());
        lbl_resultado14.setText(""+cant);
        
        cant = analizar.palabras_impares(txta_input.getText());
        lbl_resultado15.setText(""+cant);
        
        result = analizar.murcielago(txta_input.getText());
        txt_traduccion.setText(result);

    }//GEN-LAST:event_btn_funcActionPerformed

    private void e_i2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_i2ActionPerformed
        // TODO add your handling code here:
        if(txta_input.getText()!=null){
           String auxiliar = txta_input.getText();
           txta_input.setText(auxiliar+"\n"+edit_opcion);
        }
        else{
            txta_input.setText(edit_opcion);
        }
        
        txta_input.selectAll();
    }//GEN-LAST:event_e_i2ActionPerformed

    private void e_i5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_i5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_i5ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_cadenas_traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_cadenas_traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_cadenas_traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_cadenas_traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_cadenas_traductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem a_i1;
    private javax.swing.JMenuItem a_i2;
    private javax.swing.JMenuItem a_i3;
    private javax.swing.JButton btn_func;
    private javax.swing.JMenuItem e_i1;
    private javax.swing.JMenuItem e_i2;
    private javax.swing.JMenuItem e_i3;
    private javax.swing.JMenuItem e_i4;
    private javax.swing.JMenuItem e_i5;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl14;
    private javax.swing.JLabel lbl15;
    private javax.swing.JLabel lbl16;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lbl_resultado;
    private javax.swing.JLabel lbl_resultado10;
    private javax.swing.JLabel lbl_resultado11;
    private javax.swing.JLabel lbl_resultado12;
    private javax.swing.JLabel lbl_resultado13;
    private javax.swing.JLabel lbl_resultado14;
    private javax.swing.JLabel lbl_resultado15;
    private javax.swing.JLabel lbl_resultado2;
    private javax.swing.JLabel lbl_resultado3;
    private javax.swing.JLabel lbl_resultado4;
    private javax.swing.JLabel lbl_resultado5;
    private javax.swing.JLabel lbl_resultado6;
    private javax.swing.JLabel lbl_resultado7;
    private javax.swing.JLabel lbl_resultado8;
    private javax.swing.JLabel lbl_resultado9;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_titulo2;
    private javax.swing.JLabel lbl_welcome;
    private javax.swing.JMenu menu_archi;
    private javax.swing.JMenu menu_edit;
    private javax.swing.JTextArea txt_traduccion;
    private javax.swing.JTextArea txta_input;
    // End of variables declaration//GEN-END:variables
}
